export const newsArticles = [
	{
		id: 1,
		title: "Breaking News: Tech Innovation",
		description: "A new technology is reshaping the industry...",
		url: "https://example.com/news1",
		image: "https://via.placeholder.com/150",
		author: "John Tech",
		publishedAt: "2024-02-15T10:30:00Z",
	},
	{
		id: 2,
		title: "Economy Update: Market Trends",
		description: "The global market trends are showing promising growth...",
		url: "https://example.com/news2",
		image: "https://via.placeholder.com/150",
		author: "Emily Finance",
		publishedAt: "2024-02-14T15:45:00Z",
	},
	{
		id: 3,
		title: "Climate Change: Renewable Energy Breakthrough",
		description:
			"Scientists develop a groundbreaking sustainable energy solution...",
		url: "https://example.com/news3",
		image: "https://via.placeholder.com/150",
		author: "Alex Green",
		publishedAt: "2024-02-13T09:15:00Z",
	},
	{
		id: 4,
		title: "Space Exploration: Mars Mission Update",
		description:
			"NASA reveals new details about upcoming Mars exploration...",
		url: "https://example.com/news4",
		image: "https://via.placeholder.com/150",
		author: "Sarah Space",
		publishedAt: "2024-02-12T14:20:00Z",
	},
	{
		id: 5,
		title: "Health Tech: AI in Medical Diagnostics",
		description:
			"Artificial Intelligence is revolutionizing medical diagnostics...",
		url: "https://example.com/news5",
		image: "https://via.placeholder.com/150",
		author: "Dr. Michael Health",
		publishedAt: "2024-02-11T11:55:00Z",
	},
	{
		id: 6,
		title: "Politics: Election Results",
		description: "The latest election results are in...",
		url: "https://example.com/news6",
		image: "https://via.placeholder.com/150",
		author: "Jane Doe",
		publishedAt: "2024-02-10T18:00:00Z",
	},
	{
		id: 7,
		title: "Sports: Championship Game",
		description: "The championship game is underway...",
		url: "https://example.com/news7",
		image: "https://via.placeholder.com/150",
		author: "Mike Smith",
		publishedAt: "2024-02-09T20:30:00Z",
	},
	{
		id: 8,
		title: "Entertainment: New Movie Release",
		description: "A highly anticipated new movie has been released...",
		url: "https://example.com/news8",
		image: "https://via.placeholder.com/150",
		author: "Sarah Jones",
		publishedAt: "2024-02-08T16:45:00Z",
	},
	{
		id: 9,
		title: "Business: Stock Market Update",
		description: "The stock market is experiencing significant changes...",
		url: "https://example.com/news9",
		image: "https://via.placeholder.com/150",
		author: "David Lee",
		publishedAt: "2024-02-07T12:15:00Z",
	},
	{
		id: 10,
		title: "Technology: New Software Launch",
		description: "A new software has been launched...",
		url: "https://example.com/news10",
		image: "https://via.placeholder.com/150",
		author: "Kevin Brown",
		publishedAt: "2024-02-06T09:00:00Z",
	},
];
